from __future__ import annotations
from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import OOTxMM

class OOTxMMItem(Item):
    game = "OOTxMM"
    
class OOTxMMItemData:
    def __init__(
        self,
        id: int | None,
        symbolic_id: str,
        display_name: str,
        type: ItemClassification = ItemClassification.progression,
    ):
        self.id = id
        self.symbolic_id = symbolic_id
        self.display_name = display_name
        self.type = type
        
filler = ItemClassification.filler
progression = ItemClassification.progression
useful = ItemClassification.useful
trap = ItemClassification.trap
skip_balancing = ItemClassification.skip_balancing
progression_skip_balancing = ItemClassification.progression_skip_balancing

OOTxMMItemList: list[OOTxMMItemData] = [
    OOTxMMItemData(1, "OOT_ARROW_FIRE", "Fire Arrows (OoT)"),
    OOTxMMItemData(2, "OOT_ARROW_ICE", "Ice Arrows (OoT)"),
    OOTxMMItemData(3, "OOT_ARROW_LIGHT", "Light Arrows (OoT)"),
    OOTxMMItemData(4, "OOT_ARROWS_5", "5 Arrows (OoT)", type=filler),
    OOTxMMItemData(5, "OOT_ARROWS_10", "10 Arrows (OoT)", type=filler),
    OOTxMMItemData(6, "OOT_ARROWS_30", "30 Arrows (OoT)", type=filler),
    OOTxMMItemData(7, "OOT_BIG_POE", "Big Poe (OoT)", type=filler),
    OOTxMMItemData(8, "OOT_BLUE_FIRE", "Blue Fire", type=filler),
    OOTxMMItemData(9, "OOT_BOMB", "Bomb (OoT)", type=filler),
    OOTxMMItemData(10, "OOT_BOMB_BAG", "Bomb Bag (OoT)"),
    OOTxMMItemData(11, "OOT_BOMBCHU_5", "5 Bombchu (OoT)"),
    OOTxMMItemData(12, "OOT_BOMBCHU_10", "10 Bombchu (OoT)"),
    OOTxMMItemData(13, "OOT_BOMBCHU_20", "20 Bombchu (OoT)"),
    OOTxMMItemData(14, "OOT_BOMBCHU_BAG", "Bombchu Bag (OoT)"),
    OOTxMMItemData(15, "OOT_BOMBS_5", "5 Bombs (OoT)", type=filler),
    OOTxMMItemData(16, "OOT_BOMBS_10", "10 Bombs (OoT)", type=filler),
    OOTxMMItemData(17, "OOT_BOMBS_20", "20 Bombs (OoT)", type=filler),
    OOTxMMItemData(18, "OOT_BOMBS_30", "30 Bombs (OoT)", type=filler),
    OOTxMMItemData(19, "OOT_BOOMERANG", "Boomerang"),
    OOTxMMItemData(20, "OOT_BOOTS_HOVER", "Hover Boots (OoT)"),
    OOTxMMItemData(21, "OOT_BOOTS_IRON", "Iron Boots (OoT)"),
    OOTxMMItemData(22, "OOT_BOSS_KEY_FIRE", "Boss Key (Fire Temple)"),
    OOTxMMItemData(23, "OOT_BOSS_KEY_FOREST", "Boss Key (Forest Temple)"),
    OOTxMMItemData(24, "OOT_BOSS_KEY_GANON", "Boss Key (Ganon's Castle)"),
    OOTxMMItemData(25, "OOT_BOSS_KEY_SHADOW", "Boss Key (Shadow Temple)"),
    OOTxMMItemData(26, "OOT_BOSS_KEY_SPIRIT", "Boss Key (Spirit Temple)"),
    OOTxMMItemData(27, "OOT_BOSS_KEY_WATER", "Boss Key (Water Temple)"),
    OOTxMMItemData(28, "OOT_BOTTLE_BIG_POE", "Bottled Big Poe (OoT)"),
    OOTxMMItemData(29, "OOT_BOTTLE_BLUE_FIRE", "Bottle of Blue Fire"),
    OOTxMMItemData(30, "OOT_BOTTLE_EMPTY", "Empty Bottle (OoT)"),
    OOTxMMItemData(31, "OOT_BOTTLE_FAIRY", "Bottled Fairy (OoT)"),
    OOTxMMItemData(32, "OOT_BOTTLE_MILK", "Bottle of Milk (OoT)"),
    OOTxMMItemData(33, "OOT_BOTTLE_POE", "Bottled Poe (OoT)"),
    OOTxMMItemData(34, "OOT_BOTTLE_POTION_BLUE", "Bottle of Blue Potion (OoT)"),
    OOTxMMItemData(35, "OOT_BOTTLE_POTION_GREEN", "Bottle of Green Potion (OoT)"),
    OOTxMMItemData(36, "OOT_BOTTLE_POTION_RED", "Bottle of Red Potion (OoT)"),
    OOTxMMItemData(37, "OOT_BOW", "Fairy Bow (OoT)"),
    OOTxMMItemData(38, "OOT_BROKEN_GORON_SWORD", "Broken Goron's Sword"),
    OOTxMMItemData(39, "OOT_BUG", "Bugs (OoT)", type=filler),
    OOTxMMItemData(40, "OOT_BUTTON_A", "A Button (OoT)"),
    OOTxMMItemData(41, "OOT_BUTTON_C_DOWN", "C-Down Button (OoT)"),
    OOTxMMItemData(42, "OOT_BUTTON_C_LEFT", "C-Left Button (OoT)"),
    OOTxMMItemData(43, "OOT_BUTTON_C_RIGHT", "C-Right Button (OoT)"),
    OOTxMMItemData(44, "OOT_BUTTON_C_UP", "C-Up Button (OoT)"),
    OOTxMMItemData(45, "OOT_CHICKEN", "Chicken"),
    OOTxMMItemData(46, "OOT_CLAIM_CHECK", "Claim Check"),
    OOTxMMItemData(47, "OOT_COIN_BLUE", "Coin (Blue)"),
    OOTxMMItemData(48, "OOT_COIN_GREEN", "Coin (Green)"),
    OOTxMMItemData(49, "OOT_COIN_RED", "Coin (Red)"),
    OOTxMMItemData(50, "OOT_COIN_YELLOW", "Coin (Yellow)"),
    OOTxMMItemData(51, "OOT_COJIRO", "Cojiro"),
    OOTxMMItemData(52, "OOT_COMPASS_BOTW", "Compass (Bottom of the Well)", type=useful),
    OOTxMMItemData(53, "OOT_COMPASS_DC", "Compass (Dodongo's Cavern)", type=useful),
    OOTxMMItemData(54, "OOT_COMPASS_DT", "Compass (Deku Tree)", type=useful),
    OOTxMMItemData(55, "OOT_COMPASS_FIRE", "Compass (Fire Temple)", type=useful),
    OOTxMMItemData(56, "OOT_COMPASS_FOREST", "Compass (Forest Temple)", type=useful),
    OOTxMMItemData(57, "OOT_COMPASS_IC", "Compass (Ice Cavern)", type=useful),
    OOTxMMItemData(58, "OOT_COMPASS_JJ", "Compass (Jabu-Jabu's Belly)", type=useful),
    OOTxMMItemData(59, "OOT_COMPASS_SHADOW", "Compass (Shadow Temple)", type=useful),
    OOTxMMItemData(60, "OOT_COMPASS_SPIRIT", "Compass (Spirit Temple)", type=useful),
    OOTxMMItemData(61, "OOT_COMPASS_WATER", "Compass (Water Temple)", type=useful),
    OOTxMMItemData(62, "OOT_DEFENSE_UPGRADE", "Double Defense (OoT)", type=useful),
    OOTxMMItemData(63, "OOT_DEKU_SEEDS_5", "5 Deku Seeds (OoT)", type=filler),
    OOTxMMItemData(64, "OOT_DEKU_SEEDS_30", "30 Deku Seeds", type=filler),
    OOTxMMItemData(65, "OOT_EYE_DROPS", "Eye Drops"),
    OOTxMMItemData(66, "OOT_EYEBALL_FROG", "Eyeball Frog"),
    OOTxMMItemData(67, "OOT_FAIRY", "Fairy (OoT)", type=filler),
    OOTxMMItemData(68, "OOT_FAIRY_BIG", "Big Fairy (OoT)", type=filler),
    OOTxMMItemData(69, "OOT_FISH", "Fish (OoT)", type=filler),
    OOTxMMItemData(70, "OOT_FISHING_POND_ADULT_FISH_4LBS", "Adult Fish (4 pounds)", type=filler),
    OOTxMMItemData(71, "OOT_FISHING_POND_ADULT_FISH_5LBS", "Adult Fish (5 pounds)", type=filler),
    OOTxMMItemData(72, "OOT_FISHING_POND_ADULT_FISH_6LBS", "Adult Fish (6 pounds)", type=filler),
    OOTxMMItemData(73, "OOT_FISHING_POND_ADULT_FISH_7LBS", "Adult Fish (7 pounds)", type=filler),
    OOTxMMItemData(74, "OOT_FISHING_POND_ADULT_FISH_8LBS", "Adult Fish (8 pounds)"),
    OOTxMMItemData(75, "OOT_FISHING_POND_ADULT_FISH_9LBS", "Adult Fish (9 pounds)"),
    OOTxMMItemData(76, "OOT_FISHING_POND_ADULT_FISH_10LBS", "Adult Fish (10 pounds)"),
    OOTxMMItemData(77, "OOT_FISHING_POND_ADULT_FISH_11LBS", "Adult Fish (11 pounds)"),
    OOTxMMItemData(78, "OOT_FISHING_POND_ADULT_FISH_12LBS", "Adult Fish (12 pounds)"),
    OOTxMMItemData(79, "OOT_FISHING_POND_ADULT_FISH_13LBS", "Adult Fish (13 pounds)"),
    OOTxMMItemData(80, "OOT_FISHING_POND_ADULT_FISH_14LBS", "Adult Fish (14 pounds)"),
    OOTxMMItemData(81, "OOT_FISHING_POND_ADULT_FISH_15LBS", "Adult Fish (15 pounds)"),
    OOTxMMItemData(82, "OOT_FISHING_POND_ADULT_FISH_16LBS", "Adult Fish (16 pounds)"),
    OOTxMMItemData(83, "OOT_FISHING_POND_ADULT_FISH_17LBS", "Adult Fish (17 pounds)"),
    OOTxMMItemData(84, "OOT_FISHING_POND_ADULT_FISH_18LBS", "Adult Fish (18 pounds)"),
    OOTxMMItemData(85, "OOT_FISHING_POND_ADULT_FISH_19LBS", "Adult Fish (19 pounds)"),
    OOTxMMItemData(86, "OOT_FISHING_POND_ADULT_FISH_20LBS", "Adult Fish (20 pounds)"),
    OOTxMMItemData(87, "OOT_FISHING_POND_ADULT_FISH_21LBS", "Adult Fish (21 pounds)"),
    OOTxMMItemData(88, "OOT_FISHING_POND_ADULT_FISH_22LBS", "Adult Fish (22 pounds)"),
    OOTxMMItemData(89, "OOT_FISHING_POND_ADULT_FISH_23LBS", "Adult Fish (23 pounds)"),
    OOTxMMItemData(90, "OOT_FISHING_POND_ADULT_FISH_24LBS", "Adult Fish (24 pounds)"),
    OOTxMMItemData(91, "OOT_FISHING_POND_ADULT_FISH_25LBS", "Adult Fish (25 pounds)"),
    OOTxMMItemData(92, "OOT_FISHING_POND_ADULT_LOACH_29LBS", "Adult Loach (29 pounds)"),
    OOTxMMItemData(93, "OOT_FISHING_POND_ADULT_LOACH_30LBS", "Adult Loach (30 pounds)"),
    OOTxMMItemData(94, "OOT_FISHING_POND_ADULT_LOACH_31LBS", "Adult Loach (31 pounds)"),
    OOTxMMItemData(95, "OOT_FISHING_POND_ADULT_LOACH_32LBS", "Adult Loach (32 pounds)"),
    OOTxMMItemData(96, "OOT_FISHING_POND_ADULT_LOACH_33LBS", "Adult Loach (33 pounds)"),
    OOTxMMItemData(97, "OOT_FISHING_POND_ADULT_LOACH_34LBS", "Adult Loach (34 pounds)"),
    OOTxMMItemData(98, "OOT_FISHING_POND_ADULT_LOACH_35LBS", "Adult Loach (35 pounds)"),
    OOTxMMItemData(99, "OOT_FISHING_POND_ADULT_LOACH_36LBS", "Adult Loach (36 pounds)"),
    OOTxMMItemData(100, "OOT_FISHING_POND_CHILD_FISH_2LBS", "Child Fish (2 pounds)", type=filler),
    OOTxMMItemData(101, "OOT_FISHING_POND_CHILD_FISH_3LBS", "Child Fish (3 pounds)", type=filler),
    OOTxMMItemData(102, "OOT_FISHING_POND_CHILD_FISH_4LBS", "Child Fish (4 pounds)", type=filler),
    OOTxMMItemData(103, "OOT_FISHING_POND_CHILD_FISH_5LBS", "Child Fish (5 pounds)", type=filler),
    OOTxMMItemData(104, "OOT_FISHING_POND_CHILD_FISH_6LBS", "Child Fish (6 pounds)", type=filler),
    OOTxMMItemData(105, "OOT_FISHING_POND_CHILD_FISH_7LBS", "Child Fish (7 pounds)"),
    OOTxMMItemData(106, "OOT_FISHING_POND_CHILD_FISH_8LBS", "Child Fish (8 pounds)"),
    OOTxMMItemData(107, "OOT_FISHING_POND_CHILD_FISH_9LBS", "Child Fish (9 pounds)"),
    OOTxMMItemData(108, "OOT_FISHING_POND_CHILD_FISH_10LBS", "Child Fish (10 pounds)"),
    OOTxMMItemData(109, "OOT_FISHING_POND_CHILD_FISH_11LBS", "Child Fish (11 pounds)"),
    OOTxMMItemData(110, "OOT_FISHING_POND_CHILD_FISH_12LBS", "Child Fish (12 pounds)"),
    OOTxMMItemData(111, "OOT_FISHING_POND_CHILD_FISH_13LBS", "Child Fish (13 pounds)"),
    OOTxMMItemData(112, "OOT_FISHING_POND_CHILD_FISH_14LBS", "Child Fish (14 pounds)"),
    OOTxMMItemData(113, "OOT_FISHING_POND_CHILD_LOACH_14LBS", "Child Loach (14 pounds)"),
    OOTxMMItemData(114, "OOT_FISHING_POND_CHILD_LOACH_15LBS", "Child Loach (15 pounds)"),
    OOTxMMItemData(115, "OOT_FISHING_POND_CHILD_LOACH_16LBS", "Child Loach (16 pounds)"),
    OOTxMMItemData(116, "OOT_FISHING_POND_CHILD_LOACH_17LBS", "Child Loach (17 pounds)"),
    OOTxMMItemData(117, "OOT_FISHING_POND_CHILD_LOACH_18LBS", "Child Loach (18 pounds)"),
    OOTxMMItemData(118, "OOT_FISHING_POND_CHILD_LOACH_19LBS", "Child Loach (19 pounds)"),
    OOTxMMItemData(119, "OOT_GERUDO_CARD", "Gerudo's Membership Card"),
    OOTxMMItemData(120, "OOT_GS_TOKEN", "Gold Skulltula Token"),
    OOTxMMItemData(121, "OOT_HAMMER", "Megaton Hammer (OoT)"),
    OOTxMMItemData(122, "OOT_HEART_CONTAINER", "Heart Container (OoT)", type=useful),
    OOTxMMItemData(123, "OOT_HEART_PIECE", "Piece of Heart (OoT)", type=useful),
    OOTxMMItemData(124, "OOT_HOOKSHOT", "Progressive Hookshot (OoT)"),
    OOTxMMItemData(125, "OOT_KEY_RING_BOTW", "Key Ring (Well)"),
    OOTxMMItemData(126, "OOT_KEY_RING_FIRE", "Key Ring (Fire)"),
    OOTxMMItemData(127, "OOT_KEY_RING_FOREST", "Key Ring (Forest)"),
    OOTxMMItemData(128, "OOT_KEY_RING_GANON", "Key Ring (Ganon)"),
    OOTxMMItemData(129, "OOT_KEY_RING_GF", "Key Ring (Hideout)"),
    OOTxMMItemData(130, "OOT_KEY_RING_GTG", "Key Ring (GTG)"),
    OOTxMMItemData(131, "OOT_KEY_RING_SHADOW", "Key Ring (Shadow)"),
    OOTxMMItemData(132, "OOT_KEY_RING_SPIRIT", "Key Ring (Spirit)"),
    OOTxMMItemData(133, "OOT_KEY_RING_TCG", "Key Ring (Chest Game)"),
    OOTxMMItemData(134, "OOT_KEY_RING_WATER", "Key Ring (Water)"),
    OOTxMMItemData(135, "OOT_LENS", "Lens of Truth (OoT)"),
    OOTxMMItemData(136, "OOT_MAGIC_BEAN", "Magic Beans (OoT)"),
    OOTxMMItemData(137, "OOT_MAGIC_JAR_LARGE", "Large Magic Jar (OoT)", type=filler),
    OOTxMMItemData(138, "OOT_MAGIC_JAR_SMALL", "Small Magic Jar (OoT)", type=filler),
    OOTxMMItemData(139, "OOT_MAGIC_UPGRADE", "Magic Upgrade (OoT)"),
    OOTxMMItemData(140, "OOT_MAP_BOTW", "Map (Bottom of the Well)", type=useful),
    OOTxMMItemData(141, "OOT_MAP_DC", "Map (Dodongo's Cavern)", type=useful),
    OOTxMMItemData(142, "OOT_MAP_DT", "Map (Deku Tree)", type=useful),
    OOTxMMItemData(143, "OOT_MAP_FIRE", "Map (Fire Temple)", type=useful),
    OOTxMMItemData(144, "OOT_MAP_FOREST", "Map (Forest Temple)", type=useful),
    OOTxMMItemData(145, "OOT_MAP_IC", "Map (Ice Cavern)", type=useful),
    OOTxMMItemData(146, "OOT_MAP_JJ", "Map (Jabu-Jabu's Belly)", type=useful),
    OOTxMMItemData(147, "OOT_MAP_SHADOW", "Map (Shadow Temple)", type=useful),
    OOTxMMItemData(148, "OOT_MAP_SPIRIT", "Map (Spirit Temple)", type=useful),
    OOTxMMItemData(149, "OOT_MAP_WATER", "Map (Water Temple)", type=useful),
    OOTxMMItemData(150, "OOT_MASK_BLAST", "Blast Mask (OoT)"),
    OOTxMMItemData(151, "OOT_MASK_BUNNY", "Bunny Hood (OoT)"),
    OOTxMMItemData(152, "OOT_MASK_GERUDO", "Gerudo Mask", type=filler),
    OOTxMMItemData(153, "OOT_MASK_GORON", "Goron Mask (OoT)", type=filler),
    OOTxMMItemData(154, "OOT_MASK_KEATON", "Keaton Mask (OoT)"),
    OOTxMMItemData(155, "OOT_MASK_SKULL", "Skull Mask"),
    OOTxMMItemData(156, "OOT_MASK_SPOOKY", "Spooky Mask"),
    OOTxMMItemData(157, "OOT_MASK_STONE", "Stone Mask (OoT)"),
    OOTxMMItemData(158, "OOT_MASK_TRUTH", "Mask of Truth (OoT)"),
    OOTxMMItemData(159, "OOT_MASK_ZORA", "Zora Mask (OoT)", type=filler),
    OOTxMMItemData(160, "OOT_MEDALLION_FIRE", "Fire Medallion"),
    OOTxMMItemData(161, "OOT_MEDALLION_FOREST", "Forest Medallion"),
    OOTxMMItemData(162, "OOT_MEDALLION_LIGHT", "Light Medallion"),
    OOTxMMItemData(163, "OOT_MEDALLION_SHADOW", "Shadow Medallion"),
    OOTxMMItemData(164, "OOT_MEDALLION_SPIRIT", "Spirit Medallion"),
    OOTxMMItemData(165, "OOT_MEDALLION_WATER", "Water Medallion"),
    OOTxMMItemData(166, "OOT_MILK", "Lon Lon Milk (OoT)", type=filler),
    OOTxMMItemData(167, "OOT_NUT_UPGRADE", "Deku Nut Upgrade (OoT)", type=filler),
    OOTxMMItemData(168, "OOT_NUTS_5", "5 Deku Nuts (OoT)", type=filler),
    OOTxMMItemData(169, "OOT_NUTS_10", "10 Deku Nuts (OoT)", type=filler),
    OOTxMMItemData(170, "OOT_OCARINA", "Progressive Ocarina (OoT)"),
    OOTxMMItemData(171, "OOT_ODD_MUSHROOM", "Odd Mushroom"),
    OOTxMMItemData(172, "OOT_ODD_POTION", "Odd Potion"),
    OOTxMMItemData(173, "OOT_POACHER_SAW", "Poacher's Saw"),
    OOTxMMItemData(174, "OOT_POCKET_CUCCO", "Pocket Cucco"),
    OOTxMMItemData(175, "OOT_POCKET_EGG", "Pocket Egg"),
    OOTxMMItemData(176, "OOT_POE", "Poe (OoT)", type=filler),
    OOTxMMItemData(177, "OOT_POTION_BLUE", "Blue Potion (OoT)", type=filler),
    OOTxMMItemData(178, "OOT_POTION_GREEN", "Green Potion (OoT)", type=filler),
    OOTxMMItemData(179, "OOT_POTION_RED", "Red Potion (OoT)", type=filler),
    OOTxMMItemData(180, "OOT_POUCH_SILVER_BOTW", "Silver Rupee Pouch (Bottom of the Well)"),
    OOTxMMItemData(181, "OOT_POUCH_SILVER_DC", "Silver Rupee Pouch (Dodongo's Cavern)"),
    OOTxMMItemData(182, "OOT_POUCH_SILVER_GANON_FIRE", "Silver Rupee Pouch (Ganon's Castle - Fire Trial)"),
    OOTxMMItemData(183, "OOT_POUCH_SILVER_GANON_FOREST", "Silver Rupee Pouch (Ganon's Castle - Forest Trial)"),
    OOTxMMItemData(184, "OOT_POUCH_SILVER_GANON_LIGHT", "Silver Rupee Pouch (Ganon's Castle - Light Trial)"),
    OOTxMMItemData(185, "OOT_POUCH_SILVER_GANON_SHADOW", "Silver Rupee Pouch (Ganon's Castle - Shadow Trial)"),
    OOTxMMItemData(186, "OOT_POUCH_SILVER_GANON_SPIRIT", "Silver Rupee Pouch (Ganon's Castle - Spirit Trial)"),
    OOTxMMItemData(187, "OOT_POUCH_SILVER_GANON_WATER", "Silver Rupee Pouch (Ganon's Castle - Water Trial)"),
    OOTxMMItemData(188, "OOT_POUCH_SILVER_GTG_LAVA", "Silver Rupee Pouch (Gerudo Training Ground - Lava)"),
    OOTxMMItemData(189, "OOT_POUCH_SILVER_GTG_SLOPES", "Silver Rupee Pouch (Gerudo Training Ground - Slopes)"),
    OOTxMMItemData(190, "OOT_POUCH_SILVER_GTG_WATER", "Silver Rupee Pouch (Gerudo Training Ground - Water)"),
    OOTxMMItemData(191, "OOT_POUCH_SILVER_IC_BLOCK", "Silver Rupee Pouch (Ice Cavern - Block)"),
    OOTxMMItemData(192, "OOT_POUCH_SILVER_IC_SCYTHE", "Silver Rupee Pouch (Ice Cavern - Scythe)"),
    OOTxMMItemData(193, "OOT_POUCH_SILVER_SHADOW_BLADES", "Silver Rupee Pouch (Shadow Temple - Invisible Blades)"),
    OOTxMMItemData(194, "OOT_POUCH_SILVER_SHADOW_PIT", "Silver Rupee Pouch (Shadow Temple - Large Pits)"),
    OOTxMMItemData(195, "OOT_POUCH_SILVER_SHADOW_SCYTHE", "Silver Rupee Pouch (Shadow Temple - Scythe)"),
    OOTxMMItemData(196, "OOT_POUCH_SILVER_SHADOW_SPIKES", "Silver Rupee Pouch (Shadow Temple - Spikes)"),
    OOTxMMItemData(197, "OOT_POUCH_SILVER_SPIRIT_ADULT", "Silver Rupee Pouch (Spirit Temple - Adult)"),
    OOTxMMItemData(198, "OOT_POUCH_SILVER_SPIRIT_BOULDERS", "Silver Rupee Pouch (Spirit Temple - Boulders)"),
    OOTxMMItemData(199, "OOT_POUCH_SILVER_SPIRIT_CHILD", "Silver Rupee Pouch (Spirit Temple - Child)"),
    OOTxMMItemData(200, "OOT_POUCH_SILVER_SPIRIT_LOBBY", "Silver Rupee Pouch (Spirit Temple - Lobby)"),
    OOTxMMItemData(201, "OOT_POUCH_SILVER_SPIRIT_SUN", "Silver Rupee Pouch (Spirit Temple - Sun Block)"),
    OOTxMMItemData(202, "OOT_PRESCRIPTION", "Prescription"),
    OOTxMMItemData(203, "OOT_RECOVERY_HEART", "Recovery Heart (OoT)", type=filler),
    OOTxMMItemData(204, "OOT_RUPEE_BLUE", "Blue Rupee (OoT)", type=filler),
    OOTxMMItemData(205, "OOT_RUPEE_GREEN", "Green Rupee (OoT)", type=filler),
    OOTxMMItemData(206, "OOT_RUPEE_HUGE", "Gold Rupee (OoT)", type=filler),
    OOTxMMItemData(207, "OOT_RUPEE_MAGICAL", "Magical Silver Rupee"),
    OOTxMMItemData(208, "OOT_RUPEE_PURPLE", "Purple Rupee (OoT)", type=filler),
    OOTxMMItemData(209, "OOT_RUPEE_RAINBOW", "Rainbow Rupee (OoT)", type=useful),
    OOTxMMItemData(210, "OOT_RUPEE_RED", "Red Rupee (OoT)", type=filler),
    OOTxMMItemData(211, "OOT_RUPEE_SILVER_BOTW", "Silver Rupee (Bottom of the Well)"),
    OOTxMMItemData(212, "OOT_RUPEE_SILVER_DC", "Silver Rupee (Dodongo's Cavern)"),
    OOTxMMItemData(213, "OOT_RUPEE_SILVER_GANON_FIRE", "Silver Rupee (Ganon's Castle - Fire Trial)"),
    OOTxMMItemData(214, "OOT_RUPEE_SILVER_GANON_FOREST", "Silver Rupee (Ganon's Castle - Forest Trial)"),
    OOTxMMItemData(215, "OOT_RUPEE_SILVER_GANON_LIGHT", "Silver Rupee (Ganon's Castle - Light Trial)"),
    OOTxMMItemData(216, "OOT_RUPEE_SILVER_GANON_SHADOW", "Silver Rupee (Ganon's Castle - Shadow Trial)"),
    OOTxMMItemData(217, "OOT_RUPEE_SILVER_GANON_SPIRIT", "Silver Rupee (Ganon's Castle - Spirit Trial)"),
    OOTxMMItemData(218, "OOT_RUPEE_SILVER_GANON_WATER", "Silver Rupee (Ganon's Castle - Water Trial)"),
    OOTxMMItemData(219, "OOT_RUPEE_SILVER_GTG_LAVA", "Silver Rupee (Gerudo Training Ground - Lava)"),
    OOTxMMItemData(220, "OOT_RUPEE_SILVER_GTG_SLOPES", "Silver Rupee (Gerudo Training Ground - Slopes)"),
    OOTxMMItemData(221, "OOT_RUPEE_SILVER_GTG_WATER", "Silver Rupee (Gerudo Training Ground - Water)"),
    OOTxMMItemData(222, "OOT_RUPEE_SILVER_IC_BLOCK", "Silver Rupee (Ice Cavern - Block)"),
    OOTxMMItemData(223, "OOT_RUPEE_SILVER_IC_SCYTHE", "Silver Rupee (Ice Cavern - Scythe)"),
    OOTxMMItemData(224, "OOT_RUPEE_SILVER_SHADOW_BLADES", "Silver Rupee (Shadow Temple - Invisible Blades)"),
    OOTxMMItemData(225, "OOT_RUPEE_SILVER_SHADOW_PIT", "Silver Rupee (Shadow Temple - Large Pits)"),
    OOTxMMItemData(226, "OOT_RUPEE_SILVER_SHADOW_SCYTHE", "Silver Rupee (Shadow Temple - Scythe)"),
    OOTxMMItemData(227, "OOT_RUPEE_SILVER_SHADOW_SPIKES", "Silver Rupee (Shadow Temple - Spikes)"),
    OOTxMMItemData(228, "OOT_RUPEE_SILVER_SPIRIT_ADULT", "Silver Rupee (Spirit Temple - Adult)"),
    OOTxMMItemData(229, "OOT_RUPEE_SILVER_SPIRIT_BOULDERS", "Silver Rupee (Spirit Temple - Boulders)"),
    OOTxMMItemData(230, "OOT_RUPEE_SILVER_SPIRIT_CHILD", "Silver Rupee (Spirit Temple - Child)"),
    OOTxMMItemData(231, "OOT_RUPEE_SILVER_SPIRIT_LOBBY", "Silver Rupee (Spirit Temple - Lobby)"),
    OOTxMMItemData(232, "OOT_RUPEE_SILVER_SPIRIT_SUN", "Silver Rupee (Spirit Temple - Sun Block)"),
    OOTxMMItemData(233, "OOT_RUTO_LETTER", "Ruto's Letter"),
    OOTxMMItemData(234, "OOT_SCALE", "Progressive Scale (Oot)"),
    OOTxMMItemData(235, "OOT_SHIELD", "Progressive Shield (OoT)"),
    OOTxMMItemData(236, "OOT_SHIELD_DEKU", "Deku Shield (OoT)", type=useful),
    OOTxMMItemData(237, "OOT_SHIELD_HYLIAN", "Hylian Shield", type=useful),
    OOTxMMItemData(238, "OOT_SHIELD_MIRROR", "Mirror Shield (OoT)"),
    OOTxMMItemData(239, "OOT_SKELETON_KEY", "Skeleton Key (OoT)"),
    OOTxMMItemData(240, "OOT_SLINGSHOT", "Fairy Slingshot"),
    OOTxMMItemData(241, "OOT_SMALL_KEY_BOTW", "Small Key (Bottom of the Well)"),
    OOTxMMItemData(242, "OOT_SMALL_KEY_FIRE", "Small Key (Fire Temple)"),
    OOTxMMItemData(243, "OOT_SMALL_KEY_FOREST", "Small Key (Forest Temple)"),
    OOTxMMItemData(244, "OOT_SMALL_KEY_GANON", "Small Key (Ganon's Castle)"),
    OOTxMMItemData(245, "OOT_SMALL_KEY_GF", "Small Key (Gerudo's Fortress)"),
    OOTxMMItemData(246, "OOT_SMALL_KEY_GTG", "Small Key (Gerudo's Training Ground)"),
    OOTxMMItemData(247, "OOT_SMALL_KEY_SHADOW", "Small Key (Shadow Temple)"),
    OOTxMMItemData(248, "OOT_SMALL_KEY_SPIRIT", "Small Key (Spirit Temple)"),
    OOTxMMItemData(249, "OOT_SMALL_KEY_TCG", "Small Key (Chest Game)"),
    OOTxMMItemData(250, "OOT_SMALL_KEY_WATER", "Small Key (Water Temple)"),
    OOTxMMItemData(251, "OOT_SONG_EMPTINESS", "Elegy of Emptiness (OoT)"),
    OOTxMMItemData(252, "OOT_SONG_EPONA", "Epona's Song (OoT)"),
    OOTxMMItemData(253, "OOT_SONG_SARIA", "Saria's Song"),
    OOTxMMItemData(254, "OOT_SONG_STORMS", "Song of Storms (OoT)"),
    OOTxMMItemData(255, "OOT_SONG_SUN", "Sun's Song (OoT)"),
    OOTxMMItemData(256, "OOT_SONG_TIME", "Song of Time (OoT)"),
    OOTxMMItemData(257, "OOT_SONG_TP_FIRE", "Bolero of Fire"),
    OOTxMMItemData(258, "OOT_SONG_TP_FOREST", "Minuet of Forest"),
    OOTxMMItemData(259, "OOT_SONG_TP_LIGHT", "Prelude of Light"),
    OOTxMMItemData(260, "OOT_SONG_TP_SHADOW", "Nocturne of Shadow"),
    OOTxMMItemData(261, "OOT_SONG_TP_SPIRIT", "Requiem of Spirit"),
    OOTxMMItemData(262, "OOT_SONG_TP_WATER", "Serenade of Water"),
    OOTxMMItemData(263, "OOT_SONG_ZELDA", "Zelda's Lullaby"),
    OOTxMMItemData(264, "OOT_SOUL_BOSS_BARINADE", "Soul of Barinade"),
    OOTxMMItemData(265, "OOT_SOUL_BOSS_BONGO_BONGO", "Soul of Bongo Bongo"),
    OOTxMMItemData(266, "OOT_SOUL_BOSS_KING_DODONGO", "Soul of King Dodongo"),
    OOTxMMItemData(267, "OOT_SOUL_BOSS_MORPHA", "Soul of Morpha"),
    OOTxMMItemData(268, "OOT_SOUL_BOSS_PHANTOM_GANON", "Soul of Phantom Ganon"),
    OOTxMMItemData(269, "OOT_SOUL_BOSS_QUEEN_GOHMA", "Soul of Queen Gohma"),
    OOTxMMItemData(270, "OOT_SOUL_BOSS_TWINROVA", "Soul of Twinrova"),
    OOTxMMItemData(271, "OOT_SOUL_BOSS_VOLVAGIA", "Soul of Volvagia"),
    OOTxMMItemData(272, "OOT_SOUL_ENEMY_ANUBIS", "Soul of Anubis"),
    OOTxMMItemData(273, "OOT_SOUL_ENEMY_ARMOS", "Soul of Armos (OoT)"),
    OOTxMMItemData(274, "OOT_SOUL_ENEMY_BABY_DODONGO", "Soul of Baby Dodongos"),
    OOTxMMItemData(275, "OOT_SOUL_ENEMY_BEAMOS", "Soul of Beamos (OoT)"),
    OOTxMMItemData(276, "OOT_SOUL_ENEMY_BIRI_BARI", "Soul of Biris/Baris"),
    OOTxMMItemData(277, "OOT_SOUL_ENEMY_BUBBLE", "Soul of Bubbles (OoT)"),
    OOTxMMItemData(278, "OOT_SOUL_ENEMY_DARK_LINK", "Soul of Dark Link"),
    OOTxMMItemData(279, "OOT_SOUL_ENEMY_DEAD_HAND", "Soul of Dead Hands"),
    OOTxMMItemData(280, "OOT_SOUL_ENEMY_DEKU_BABA", "Soul of Deku Babas (OoT)"),
    OOTxMMItemData(281, "OOT_SOUL_ENEMY_DEKU_SCRUB", "Soul of Deku Scrubs (OoT)"),
    OOTxMMItemData(282, "OOT_SOUL_ENEMY_DODONGO", "Soul of Dodongos (OoT)"),
    OOTxMMItemData(283, "OOT_SOUL_ENEMY_FLARE_DANCER", "Soul of Flare Dancers"),
    OOTxMMItemData(284, "OOT_SOUL_ENEMY_FLOORMASTER", "Soul of Floormasters (OoT)"),
    OOTxMMItemData(285, "OOT_SOUL_ENEMY_FLYING_POT", "Soul of Flying Pots (OoT)"),
    OOTxMMItemData(286, "OOT_SOUL_ENEMY_FREEZARD", "Soul of Freezards (OoT)"),
    OOTxMMItemData(287, "OOT_SOUL_ENEMY_GOHMA_LARVA", "Soul of Gohma Larvaes", type=filler),
    OOTxMMItemData(288, "OOT_SOUL_ENEMY_GUAY", "Soul of Guays (OoT)"),
    OOTxMMItemData(289, "OOT_SOUL_ENEMY_IRON_KNUCKLE", "Soul of Iron Knuckles (OoT)"),
    OOTxMMItemData(290, "OOT_SOUL_ENEMY_KEESE", "Soul of Keese (OoT)"),
    OOTxMMItemData(291, "OOT_SOUL_ENEMY_LEEVER", "Soul of Leevers (OoT)"),
    OOTxMMItemData(292, "OOT_SOUL_ENEMY_LIKE_LIKE", "Soul of Like Likes (OoT)"),
    OOTxMMItemData(293, "OOT_SOUL_ENEMY_LIZALFOS_DINALFOS", "Soul of Lizalfos/Dinolfos (OoT)"),
    OOTxMMItemData(294, "OOT_SOUL_ENEMY_MOBLIN", "Soul of Moblins", type=filler),
    OOTxMMItemData(295, "OOT_SOUL_ENEMY_OCTOROK", "Soul of Octoroks (OoT)"),
    OOTxMMItemData(296, "OOT_SOUL_ENEMY_PARASITE", "Soul of Jabu-Jabu's Parasites"),
    OOTxMMItemData(297, "OOT_SOUL_ENEMY_PEAHAT", "Soul of Peahats (OoT)"),
    OOTxMMItemData(298, "OOT_SOUL_ENEMY_REDEAD_GIBDO", "Soul of ReDeads/Gibdos (OoT)"),
    OOTxMMItemData(299, "OOT_SOUL_ENEMY_SHABOM", "Soul of Shaboms"),
    OOTxMMItemData(300, "OOT_SOUL_ENEMY_SHELL_BLADE", "Soul of Shell Blades (OoT)"),
    OOTxMMItemData(301, "OOT_SOUL_ENEMY_SKULL_KID", "Soul of Skull Kids (OoT)", type=filler),
    OOTxMMItemData(302, "OOT_SOUL_ENEMY_SKULLTULA", "Soul of Skulltulas (OoT)"),
    OOTxMMItemData(303, "OOT_SOUL_ENEMY_SKULLWALLTULA", "Soul of Skullwalltulas (OoT)"),
    OOTxMMItemData(304, "OOT_SOUL_ENEMY_SPIKE", "Soul of Spikes"),
    OOTxMMItemData(305, "OOT_SOUL_ENEMY_STALCHILD", "Soul of Stalchildren (OoT)"),
    OOTxMMItemData(306, "OOT_SOUL_ENEMY_STALFOS", "Soul of Stalfos (OoT)"),
    OOTxMMItemData(307, "OOT_SOUL_ENEMY_STINGER", "Soul of Stingers"),
    OOTxMMItemData(308, "OOT_SOUL_ENEMY_TAILPASARN", "Soul of Tailpasarans", type=filler),
    OOTxMMItemData(309, "OOT_SOUL_ENEMY_TEKTITE", "Soul of Tektites (OoT)"),
    OOTxMMItemData(310, "OOT_SOUL_ENEMY_THIEVES", "Soul of the Fighting Gerudos"),
    OOTxMMItemData(311, "OOT_SOUL_ENEMY_TORCH_SLUG", "Soul of Torch Slugs"),
    OOTxMMItemData(312, "OOT_SOUL_ENEMY_WALLMASTER", "Soul of Wallmasters (OoT)"),
    OOTxMMItemData(313, "OOT_SOUL_ENEMY_WOLFOS", "Soul of Wolfoses (OoT)"),
    OOTxMMItemData(314, "OOT_SOUL_MISC_BUSINESS_SCRUB", "Soul of Business Scrubs (OoT)"),
    OOTxMMItemData(315, "OOT_SOUL_MISC_GS", "Soul of Gold Skulltulas (OoT)"),
    OOTxMMItemData(316, "OOT_SOUL_NPC_ANJU", "Soul of Cucco Lady (OoT)"),
    OOTxMMItemData(317, "OOT_SOUL_NPC_ASTRONOMER", "Soul of the Astronomer (OoT)"),
    OOTxMMItemData(318, "OOT_SOUL_NPC_BANKER", "Soul of the Beggar (OoT)"),
    OOTxMMItemData(319, "OOT_SOUL_NPC_BAZAAR_SHOPKEEPER", "Soul of Bazaar Shopkeeper (OoT)"),
    OOTxMMItemData(320, "OOT_SOUL_NPC_BEAN_SALESMAN", "Soul of the Bean Salesman (OoT)"),
    OOTxMMItemData(321, "OOT_SOUL_NPC_BIGGORON", "Soul of Biggoron (OoT)"),
    OOTxMMItemData(322, "OOT_SOUL_NPC_BOMBCHU_BOWLING_LADY", "Soul of Bombchu Bowling Lady (OoT)"),
    OOTxMMItemData(323, "OOT_SOUL_NPC_BOMBCHU_SHOPKEEPER", "Soul of Bombchu Shopkeeper (OoT)"),
    OOTxMMItemData(324, "OOT_SOUL_NPC_BOMBERS", "Soul of Graveyard Kid (OoT)"),
    OOTxMMItemData(325, "OOT_SOUL_NPC_CARPENTERS", "Soul of Carpenters (OoT)"),
    OOTxMMItemData(326, "OOT_SOUL_NPC_CARPET_MAN", "Soul of the Carpet Man (OoT)"),
    OOTxMMItemData(327, "OOT_SOUL_NPC_CHEST_GAME_OWNER", "Soul of Chest Game Owner (OoT)"),
    OOTxMMItemData(328, "OOT_SOUL_NPC_CITIZEN", "Soul of the Citizens (OoT)"),
    OOTxMMItemData(329, "OOT_SOUL_NPC_COMPOSER_BROS", "Soul of Composer Bros. (OoT)"),
    OOTxMMItemData(330, "OOT_SOUL_NPC_DAMPE", "Soul of Dampe (OoT)"),
    OOTxMMItemData(331, "OOT_SOUL_NPC_DARUNIA", "Soul of Darunia"),
    OOTxMMItemData(332, "OOT_SOUL_NPC_DOG_LADY", "Soul of the Dog Lady (OoT)"),
    OOTxMMItemData(333, "OOT_SOUL_NPC_FISHING_POND_OWNER", "Soul of Fishing Pond Owner (OoT)"),
    OOTxMMItemData(334, "OOT_SOUL_NPC_GORMAN", "Soul of Ingo (OoT)"),
    OOTxMMItemData(335, "OOT_SOUL_NPC_GORON", "Soul of Goron (OoT)"),
    OOTxMMItemData(336, "OOT_SOUL_NPC_GORON_CHILD", "Soul of Goron Child (OoT)"),
    OOTxMMItemData(337, "OOT_SOUL_NPC_GORON_SHOPKEEPER", "Soul of Goron Shopkeeper (OoT)"),
    OOTxMMItemData(338, "OOT_SOUL_NPC_GROG", "Soul of the Punk Kid (OoT)"),
    OOTxMMItemData(339, "OOT_SOUL_NPC_GURU_GURU", "Soul of Guru-Guru (OoT)"),
    OOTxMMItemData(340, "OOT_SOUL_NPC_HONEY_DARLING", "Soul of Honey & Darling (OoT)"),
    OOTxMMItemData(341, "OOT_SOUL_NPC_HYLIAN_GUARD", "Soul of Hylian Guard"),
    OOTxMMItemData(342, "OOT_SOUL_NPC_KING_ZORA", "Soul of King Zora"),
    OOTxMMItemData(343, "OOT_SOUL_NPC_KOKIRI", "Soul of Kokiri"),
    OOTxMMItemData(344, "OOT_SOUL_NPC_KOKIRI_SHOPKEEPER", "Soul of Kokiri Shopkeeper"),
    OOTxMMItemData(345, "OOT_SOUL_NPC_MALON", "Soul of Malon (OoT)"),
    OOTxMMItemData(346, "OOT_SOUL_NPC_MEDIGORON", "Soul of Medigoron (OoT)"),
    OOTxMMItemData(347, "OOT_SOUL_NPC_MIDO", "Soul of Mido"),
    OOTxMMItemData(348, "OOT_SOUL_NPC_OLD_HAG", "Soul of the Old Hag (OoT)"),
    OOTxMMItemData(349, "OOT_SOUL_NPC_POE_COLLECTOR", "Soul of Poe Collector (OoT)"),
    OOTxMMItemData(350, "OOT_SOUL_NPC_POTION_SHOPKEEPER", "Soul of Potion Shopkeeper"),
    OOTxMMItemData(351, "OOT_SOUL_NPC_ROOFTOP_MAN", "Soul of the Rooftop Man (OoT)"),
    OOTxMMItemData(352, "OOT_SOUL_NPC_RUTO", "Soul of Ruto (OoT)"),
    OOTxMMItemData(353, "OOT_SOUL_NPC_SARIA", "Soul of Saria"),
    OOTxMMItemData(354, "OOT_SOUL_NPC_SCIENTIST", "Soul of the Scientist (OoT)"),
    OOTxMMItemData(355, "OOT_SOUL_NPC_SHEIK", "Soul of Sheik"),
    OOTxMMItemData(356, "OOT_SOUL_NPC_SHOOTING_GALLERY_OWNER", "Soul of Shooting Gallery Owner (OoT)"),
    OOTxMMItemData(357, "OOT_SOUL_NPC_TALON", "Soul of Talon (OoT)"),
    OOTxMMItemData(358, "OOT_SOUL_NPC_THIEVES", "Soul of the Patrolling Gerudos"),
    OOTxMMItemData(359, "OOT_SOUL_NPC_ZELDA", "Soul of Zelda"),
    OOTxMMItemData(360, "OOT_SOUL_NPC_ZORA", "Soul of Zora (OoT)"),
    OOTxMMItemData(361, "OOT_SOUL_NPC_ZORA_SHOPKEEPER", "Soul of Zora Shopkeeper (OoT)"),
    OOTxMMItemData(362, "OOT_SPELL_FIRE", "Din's Fire (OoT)"),
    OOTxMMItemData(363, "OOT_SPELL_LOVE", "Nayru's Love (OoT)"),
    OOTxMMItemData(364, "OOT_SPELL_WIND", "Farore's Wind (OoT)"),
    OOTxMMItemData(365, "OOT_SPIN_UPGRADE", "Spin Attack Upgrade (OoT)", type=useful),
    OOTxMMItemData(366, "OOT_STICK", "Deku Stick (OoT)", type=filler),
    OOTxMMItemData(367, "OOT_STICK_UPGRADE", "Deku Stick Upgrade (OoT)", type=useful),
    OOTxMMItemData(368, "OOT_STICKS_5", "5 Deku Sticks (OoT)", type=filler),
    OOTxMMItemData(369, "OOT_STICKS_10", "10 Deku Sticks (OoT)", type=filler),
    OOTxMMItemData(370, "OOT_STONE_EMERALD", "Kokiri's Emerald"),
    OOTxMMItemData(371, "OOT_STONE_OF_AGONY", "Stone of Agony (OoT)"),
    OOTxMMItemData(372, "OOT_STONE_RUBY", "Goron's Ruby"),
    OOTxMMItemData(373, "OOT_STONE_SAPPHIRE", "Zora's Sapphire"),
    OOTxMMItemData(374, "OOT_STRENGTH", "Progressive Strength (OoT)"),
    OOTxMMItemData(375, "OOT_SWORD", "Progressive Sword (OoT)"),
    OOTxMMItemData(376, "OOT_SWORD_BIGGORON", "Biggoron's Sword"),
    OOTxMMItemData(377, "OOT_SWORD_GORON", "Progressive Goron Sword"),
    OOTxMMItemData(378, "OOT_SWORD_KNIFE", "Giant's Knife"),
    OOTxMMItemData(379, "OOT_SWORD_KOKIRI", "Kokiri Sword (OoT)"),
    OOTxMMItemData(380, "OOT_SWORD_MASTER", "Master Sword"),
    OOTxMMItemData(381, "OOT_TRAP_ICE", "Ice Trap", type=trap),
    OOTxMMItemData(382, "OOT_TRAP_RUPOOR", "Rupoor (OoT)", type=trap),
    OOTxMMItemData(383, "OOT_TUNIC_GORON", "Goron Tunic (OoT)"),
    OOTxMMItemData(384, "OOT_TUNIC_ZORA", "Zora Tunic (OoT)"),
    OOTxMMItemData(385, "OOT_WALLET", "Progressive Wallet (OoT)"),
    OOTxMMItemData(386, "OOT_WEIRD_EGG", "Weird Egg"),
    OOTxMMItemData(387, "OOT_ZELDA_LETTER", "Zelda's Letter"),
    OOTxMMItemData(388, "MM_ARROW_FIRE", "Fire Arrows (MM)"),
    OOTxMMItemData(389, "MM_ARROW_ICE", "Ice Arrows (MM)"),
    OOTxMMItemData(390, "MM_ARROW_LIGHT", "Light Arrows (MM)"),
    OOTxMMItemData(391, "MM_ARROWS_10", "10 Arrows (MM)", type=filler),
    OOTxMMItemData(392, "MM_ARROWS_30", "30 Arrows (MM)", type=filler),
    OOTxMMItemData(393, "MM_ARROWS_40", "40 Arrows (MM)", type=filler),
    OOTxMMItemData(394, "MM_BIG_POE", "Big Poe (MM)", type=filler),
    OOTxMMItemData(395, "MM_BOMB", "Bomb (MM)", type=filler),
    OOTxMMItemData(396, "MM_BOMB_BAG", "Bomb Bag (MM)"),
    OOTxMMItemData(397, "MM_BOMBCHU", "1 Bombchu (MM)"),
    OOTxMMItemData(398, "MM_BOMBCHU_5", "5 Bombchu (MM)"),
    OOTxMMItemData(399, "MM_BOMBCHU_10", "10 Bombchu (MM)"),
    OOTxMMItemData(400, "MM_BOMBCHU_20", "20 Bombchu (MM)"),
    OOTxMMItemData(401, "MM_BOMBCHU_BAG", "Bombchu Bag (MM)"),
    OOTxMMItemData(402, "MM_BOMBER_NOTEBOOK", "Bombers' Notebook", type=useful),
    OOTxMMItemData(403, "MM_BOMBS_5", "5 Bombs (MM)", type=filler),
    OOTxMMItemData(404, "MM_BOMBS_10", "10 Bombs (MM)", type=filler),
    OOTxMMItemData(405, "MM_BOMBS_20", "20 Bombs (MM)", type=filler),
    OOTxMMItemData(406, "MM_BOMBS_30", "30 Bombs (MM)", type=filler),
    OOTxMMItemData(407, "MM_BOOTS_HOVER", "Hover Boots (MM)"),
    OOTxMMItemData(408, "MM_BOOTS_IRON", "Iron Boots (MM)"),
    OOTxMMItemData(409, "MM_BOSS_KEY_GB", "Boss Key (Great Bay Temple)"),
    OOTxMMItemData(410, "MM_BOSS_KEY_SH", "Boss Key (Snowhead Temple)"),
    OOTxMMItemData(411, "MM_BOSS_KEY_ST", "Boss Key (Stone Tower Temple)"),
    OOTxMMItemData(412, "MM_BOSS_KEY_WF", "Boss Key (Woodfall Temple)"),
    OOTxMMItemData(413, "MM_BOTTLE_BIG_POE", "Bottled Big Poe (MM)"),
    OOTxMMItemData(414, "MM_BOTTLE_CHATEAU", "Bottle of Chateau Romani"),
    OOTxMMItemData(415, "MM_BOTTLE_EMPTY", "Empty Bottle (MM)"),
    OOTxMMItemData(416, "MM_BOTTLE_FAIRY", "Bottled Fairy (MM)"),
    OOTxMMItemData(417, "MM_BOTTLE_MILK", "Bottle of Milk (MM)"),
    OOTxMMItemData(418, "MM_BOTTLE_POE", "Bottled Poe (MM)"),
    OOTxMMItemData(419, "MM_BOTTLE_POTION_BLUE", "Bottle of Blue Potion (MM)"),
    OOTxMMItemData(420, "MM_BOTTLE_POTION_GREEN", "Bottle of Green Potion (MM)"),
    OOTxMMItemData(421, "MM_BOTTLE_POTION_RED", "Bottle of Red Potion (MM)"),
    OOTxMMItemData(422, "MM_BOTTLED_GOLD_DUST", "Bottle of Gold Dust"),
    OOTxMMItemData(423, "MM_BOW", "Hero's Bow (MM)"),
    OOTxMMItemData(424, "MM_BUGS", "Bugs (MM)", type=filler),
    OOTxMMItemData(425, "MM_BUTTON_A", "A Button (MM)"),
    OOTxMMItemData(426, "MM_BUTTON_C_DOWN", "C-Down Button (MM)"),
    OOTxMMItemData(427, "MM_BUTTON_C_LEFT", "C-Left Button (MM)"),
    OOTxMMItemData(428, "MM_BUTTON_C_RIGHT", "C-Right Button (MM)"),
    OOTxMMItemData(429, "MM_BUTTON_C_UP", "C-Up Button (MM)"),
    OOTxMMItemData(430, "MM_CHATEAU", "Chateau Romani Refill (MM)", type=filler),
    OOTxMMItemData(431, "MM_CLOCK", "Progressive Clock"),
    OOTxMMItemData(432, "MM_CLOCK1", "Clock (Day 1)"),
    OOTxMMItemData(433, "MM_CLOCK2", "Clock (Night 1)"),
    OOTxMMItemData(434, "MM_CLOCK3", "Clock (Day 2)"),
    OOTxMMItemData(435, "MM_CLOCK4", "Clock (Night 2)"),
    OOTxMMItemData(436, "MM_CLOCK5", "Clock (Day 3)"),
    OOTxMMItemData(437, "MM_CLOCK6", "Clock (Night 3)"),
    OOTxMMItemData(438, "MM_COMPASS_GB", "Compass (Great Bay Temple)", type=useful),
    OOTxMMItemData(439, "MM_COMPASS_SH", "Compass (Snowhead Temple)", type=useful),
    OOTxMMItemData(440, "MM_COMPASS_ST", "Compass (Stone Tower Temple)", type=useful),
    OOTxMMItemData(441, "MM_COMPASS_WF", "Compass (Woodfall Temple)", type=useful),
    OOTxMMItemData(442, "MM_DEED_LAND", "Land Title Deed"),
    OOTxMMItemData(443, "MM_DEED_MOUNTAIN", "Mountain Title Deed"),
    OOTxMMItemData(444, "MM_DEED_OCEAN", "Ocean Title Deed"),
    OOTxMMItemData(445, "MM_DEED_SWAMP", "Swamp Title Deed"),
    OOTxMMItemData(446, "MM_DEFENSE_UPGRADE", "Double Defense (MM)", type=useful),
    OOTxMMItemData(447, "MM_FAIRY", "Fairy (MM)", type=filler),
    OOTxMMItemData(448, "MM_FAIRY_BIG", "Big Fairy (MM)", type=filler),
    OOTxMMItemData(449, "MM_FISH", "Fish (MM)", type=filler),
    OOTxMMItemData(450, "MM_GREAT_FAIRY_SWORD", "Great Fairy's Sword"),
    OOTxMMItemData(451, "MM_GS_TOKEN_OCEAN", "Ocean Skulltula Token"),
    OOTxMMItemData(452, "MM_GS_TOKEN_SWAMP", "Swamp Skulltula Token"),
    OOTxMMItemData(453, "MM_HAMMER", "Megaton Hammer (MM)"),
    OOTxMMItemData(454, "MM_HEART_CONTAINER", "Heart Container (MM)", type=useful),
    OOTxMMItemData(455, "MM_HEART_PIECE", "Piece of Heart (MM)", type=useful),
    OOTxMMItemData(456, "MM_HOOKSHOT", "Hookshot (MM)"),
    OOTxMMItemData(457, "MM_KEY_RING_GB", "Key Ring (Great Bay)"),
    OOTxMMItemData(458, "MM_KEY_RING_SH", "Key Ring (Snowhead)"),
    OOTxMMItemData(459, "MM_KEY_RING_ST", "Key Ring (Stone Tower)"),
    OOTxMMItemData(460, "MM_KEY_RING_WF", "Key Ring (Woodfall)"),
    OOTxMMItemData(461, "MM_LENS", "Lens of Truth (MM)"),
    OOTxMMItemData(462, "MM_LETTER_TO_KAFEI", "Letter to Kafei"),
    OOTxMMItemData(463, "MM_LETTER_TO_MAMA", "Letter to Mama"),
    OOTxMMItemData(464, "MM_MAGIC_BEAN", "Magic Bean (MM)"),
    OOTxMMItemData(465, "MM_MAGIC_JAR_LARGE", "Large Magic Jar (MM)", type=filler),
    OOTxMMItemData(466, "MM_MAGIC_JAR_SMALL", "Small Magic Jar (MM)", type=filler),
    OOTxMMItemData(467, "MM_MAGIC_UPGRADE", "Magic Upgrade (MM)"),
    OOTxMMItemData(468, "MM_MAP_GB", "Map (Great Bay Temple)", type=useful),
    OOTxMMItemData(469, "MM_MAP_SH", "Map (Snowhead Temple)", type=useful),
    OOTxMMItemData(470, "MM_MAP_ST", "Map (Stone Tower Temple)", type=useful),
    OOTxMMItemData(471, "MM_MAP_WF", "Map (Woodfall Temple)", type=useful),
    OOTxMMItemData(472, "MM_MASK_ALL_NIGHT", "All-Night Mask"),
    OOTxMMItemData(473, "MM_MASK_BLAST", "Blast Mask (MM)"),
    OOTxMMItemData(474, "MM_MASK_BREMEN", "Bremen Mask"),
    OOTxMMItemData(475, "MM_MASK_BUNNY", "Bunny Hood (MM)"),
    OOTxMMItemData(476, "MM_MASK_CAPTAIN", "Captain's Hat"),
    OOTxMMItemData(477, "MM_MASK_COUPLE", "Couple's Mask"),
    OOTxMMItemData(478, "MM_MASK_DEKU", "Deku Mask"),
    OOTxMMItemData(479, "MM_MASK_DON_GERO", "Don Gero's Mask"),
    OOTxMMItemData(480, "MM_MASK_FIERCE_DEITY", "Fierce Deity's Mask"),
    OOTxMMItemData(481, "MM_MASK_GARO", "Garo's Mask"),
    OOTxMMItemData(482, "MM_MASK_GIANT", "Giant's Mask"),
    OOTxMMItemData(483, "MM_MASK_GIBDO", "Gibdo Mask"),
    OOTxMMItemData(484, "MM_MASK_GORON", "Goron Mask (MM)"),
    OOTxMMItemData(485, "MM_MASK_GREAT_FAIRY", "Great Fairy's Mask"),
    OOTxMMItemData(486, "MM_MASK_KAFEI", "Kafei's Mask"),
    OOTxMMItemData(487, "MM_MASK_KAMARO", "Kamaro's Mask"),
    OOTxMMItemData(488, "MM_MASK_KEATON", "Keaton Mask (MM)"),
    OOTxMMItemData(489, "MM_MASK_POSTMAN", "Postman's Hat"),
    OOTxMMItemData(490, "MM_MASK_ROMANI", "Romani's Mask"),
    OOTxMMItemData(491, "MM_MASK_SCENTS", "Mask of Scents"),
    OOTxMMItemData(492, "MM_MASK_STONE", "Stone Mask (MM)"),
    OOTxMMItemData(493, "MM_MASK_TROUPE_LEADER", "Circus Leader's Mask"),
    OOTxMMItemData(494, "MM_MASK_TRUTH", "Mask of Truth (MM)"),
    OOTxMMItemData(495, "MM_MASK_ZORA", "Zora Mask (MM)"),
    OOTxMMItemData(496, "MM_MILK", "Romani Milk", type=filler),
    OOTxMMItemData(497, "MM_MOON_TEAR", "Moon's Tear"),
    OOTxMMItemData(498, "MM_NUT", "Nut (MM)", type=filler),
    OOTxMMItemData(499, "MM_NUT_UPGRADE", "Deku Nut Upgrade (MM)", type=useful),
    OOTxMMItemData(500, "MM_NUTS_5", "5 Deku Nuts (MM)", type=filler),
    OOTxMMItemData(501, "MM_NUTS_10", "10 Deku Nuts (MM)", type=filler),
    OOTxMMItemData(502, "MM_OCARINA", "Ocarina (MM)"),
    OOTxMMItemData(503, "MM_OWL_CLOCK_TOWN", "Owl Statue (Clock Town)"),
    OOTxMMItemData(504, "MM_OWL_GREAT_BAY", "Owl Statue (Great Bay)"),
    OOTxMMItemData(505, "MM_OWL_IKANA_CANYON", "Owl Statue (Ikana Canyon)"),
    OOTxMMItemData(506, "MM_OWL_MILK_ROAD", "Owl Statue (Milk Road)"),
    OOTxMMItemData(507, "MM_OWL_MOUNTAIN_VILLAGE", "Owl Statue (Mountain Village)"),
    OOTxMMItemData(508, "MM_OWL_SNOWHEAD", "Owl Statue (Snowhead)"),
    OOTxMMItemData(509, "MM_OWL_SOUTHERN_SWAMP", "Owl Statue (Southern Swamp)"),
    OOTxMMItemData(510, "MM_OWL_STONE_TOWER", "Owl Statue (Stone Tower)"),
    OOTxMMItemData(511, "MM_OWL_WOODFALL", "Owl Statue (Woodfall)"),
    OOTxMMItemData(512, "MM_OWL_ZORA_CAPE", "Owl Statue (Zora Cape)"),
    OOTxMMItemData(513, "MM_PENDANT_OF_MEMORIES", "Pendant of Memories"),
    OOTxMMItemData(514, "MM_PICTOGRAPH_BOX", "Pictograph Box"),
    OOTxMMItemData(515, "MM_POE", "Poe (MM)", type=filler),
    OOTxMMItemData(516, "MM_POTION_BLUE", "Blue Potion (MM)", type=filler),
    OOTxMMItemData(517, "MM_POTION_GREEN", "Green Potion (MM)", type=filler),
    OOTxMMItemData(518, "MM_POTION_RED", "Red Potion (MM)", type=filler),
    OOTxMMItemData(519, "MM_POWDER_KEG", "Powder Keg"),
    OOTxMMItemData(520, "MM_RECOVERY_HEART", "Recovery Heart (MM)", type=filler),
    OOTxMMItemData(521, "MM_REMAINS_GOHT", "Goht's Remains"),
    OOTxMMItemData(522, "MM_REMAINS_GYORG", "Gyorg's Remains"),
    OOTxMMItemData(523, "MM_REMAINS_ODOLWA", "Odolwa's Remains"),
    OOTxMMItemData(524, "MM_REMAINS_TWINMOLD", "Twinmold's Remains"),
    OOTxMMItemData(525, "MM_ROOM_KEY", "Room Key"),
    OOTxMMItemData(526, "MM_RUPEE_BLUE", "Blue Rupee (MM)", type=filler),
    OOTxMMItemData(527, "MM_RUPEE_GOLD", "Gold Rupee (MM)", type=filler),
    OOTxMMItemData(528, "MM_RUPEE_GREEN", "Green Rupee (MM)", type=filler),
    OOTxMMItemData(529, "MM_RUPEE_PURPLE", "Purple Rupee (MM)", type=filler),
    OOTxMMItemData(530, "MM_RUPEE_RED", "Red Rupee (MM)", type=filler),
    OOTxMMItemData(531, "MM_RUPEE_SILVER", "Silver Rupee (MM)", type=filler),
    OOTxMMItemData(532, "MM_SCALE", "Progressive Scale (MM)"),
    OOTxMMItemData(533, "MM_SHIELD", "Progressive Shield (MM)"),
    OOTxMMItemData(534, "MM_SHIELD_DEKU", "Deku Shield (MM)"),
    OOTxMMItemData(535, "MM_SHIELD_HERO", "Hero's Shield"),
    OOTxMMItemData(536, "MM_SHIELD_MIRROR", "Mirror Shield (MM)"),
    OOTxMMItemData(537, "MM_SKELETON_KEY", "Skeleton Key (MM)"),
    OOTxMMItemData(538, "MM_SMALL_KEY_GB", "Small Key (Great Bay Temple)"),
    OOTxMMItemData(539, "MM_SMALL_KEY_SH", "Small Key (Snowhead Temple)"),
    OOTxMMItemData(540, "MM_SMALL_KEY_ST", "Small Key (Stone Tower Temple)"),
    OOTxMMItemData(541, "MM_SMALL_KEY_WF", "Small Key (Woodfall Temple)"),
    OOTxMMItemData(542, "MM_SONG_AWAKENING", "Sonata of Awakening"),
    OOTxMMItemData(543, "MM_SONG_EMPTINESS", "Elegy of Emptiness (MM)"),
    OOTxMMItemData(544, "MM_SONG_EPONA", "Epona's Song (MM)"),
    OOTxMMItemData(545, "MM_SONG_GORON", "Goron Lullaby"),
    OOTxMMItemData(546, "MM_SONG_GORON_HALF", "Progressive Goron Lullaby"),
    OOTxMMItemData(547, "MM_SONG_HEALING", "Song of Healing"),
    OOTxMMItemData(548, "MM_SONG_ORDER", "Oath to Order"),
    OOTxMMItemData(549, "MM_SONG_SOARING", "Song of Soaring"),
    OOTxMMItemData(550, "MM_SONG_STORMS", "Song of Storms (MM)"),
    OOTxMMItemData(551, "MM_SONG_SUN", "Sun's Song (MM)", type=useful),
    OOTxMMItemData(552, "MM_SONG_TIME", "Song of Time (MM)"),
    OOTxMMItemData(553, "MM_SONG_ZORA", "New Wave Bossa Nova"),
    OOTxMMItemData(554, "MM_SOUL_BOSS_GOHT", "Soul of Goht"),
    OOTxMMItemData(555, "MM_SOUL_BOSS_GYORG", "Soul of Gyorg"),
    OOTxMMItemData(556, "MM_SOUL_BOSS_IGOS", "Soul of Igos"),
    OOTxMMItemData(557, "MM_SOUL_BOSS_ODOLWA", "Soul of Odolwa"),
    OOTxMMItemData(558, "MM_SOUL_BOSS_TWINMOLD", "Soul of Twinmold"),
    OOTxMMItemData(559, "MM_SOUL_ENEMY_ARMOS", "Soul of Armos (MM)"),
    OOTxMMItemData(560, "MM_SOUL_ENEMY_BAD_BAT", "Soul of Bad Bats"),
    OOTxMMItemData(561, "MM_SOUL_ENEMY_BEAMOS", "Soul of Beamos (MM)"),
    OOTxMMItemData(562, "MM_SOUL_ENEMY_BIO_BABA", "Soul of Bio Babas"),
    OOTxMMItemData(563, "MM_SOUL_ENEMY_BOE", "Soul of Boes"),
    OOTxMMItemData(564, "MM_SOUL_ENEMY_BUBBLE", "Soul of Bubbles (MM)"),
    OOTxMMItemData(565, "MM_SOUL_ENEMY_CAPTAIN_KEETA", "Soul of Captain Keeta"),
    OOTxMMItemData(566, "MM_SOUL_ENEMY_CHUCHU", "Soul of Chuchus"),
    OOTxMMItemData(567, "MM_SOUL_ENEMY_DEEP_PYTHON", "Soul of Deep Pythons"),
    OOTxMMItemData(568, "MM_SOUL_ENEMY_DEKU_BABA", "Soul of Deku Babas (MM)"),
    OOTxMMItemData(569, "MM_SOUL_ENEMY_DEKU_SCRUB", "Soul of Deku Scrubs (MM)"),
    OOTxMMItemData(570, "MM_SOUL_ENEMY_DEXIHAND", "Soul of Dexihands"),
    OOTxMMItemData(571, "MM_SOUL_ENEMY_DODONGO", "Soul of Dodongos (MM)"),
    OOTxMMItemData(572, "MM_SOUL_ENEMY_DRAGONFLY", "Soul of Dragonflies"),
    OOTxMMItemData(573, "MM_SOUL_ENEMY_EENO", "Soul of Eenoes", type=filler),
    OOTxMMItemData(574, "MM_SOUL_ENEMY_EYEGORE", "Soul of Eyegores"),
    OOTxMMItemData(575, "MM_SOUL_ENEMY_FLOORMASTER", "Soul of Floormasters (MM)"),
    OOTxMMItemData(576, "MM_SOUL_ENEMY_FLYING_POT", "Soul of Flying Pots (MM)"),
    OOTxMMItemData(577, "MM_SOUL_ENEMY_FREEZARD", "Soul of Freezards (MM)"),
    OOTxMMItemData(578, "MM_SOUL_ENEMY_GARO", "Soul of Garo"),
    OOTxMMItemData(579, "MM_SOUL_ENEMY_GEKKO", "Soul of Gekkos"),
    OOTxMMItemData(580, "MM_SOUL_ENEMY_GOMESS", "Soul of Gomess"),
    OOTxMMItemData(581, "MM_SOUL_ENEMY_GUAY", "Soul of Guays (MM)"),
    OOTxMMItemData(582, "MM_SOUL_ENEMY_HIPLOOP", "Soul of Hiploops", type=filler),
    OOTxMMItemData(583, "MM_SOUL_ENEMY_IRON_KNUCKLE", "Soul of Iron Knuckles (MM)"),
    OOTxMMItemData(584, "MM_SOUL_ENEMY_KEESE", "Soul of Keese (MM)"),
    OOTxMMItemData(585, "MM_SOUL_ENEMY_LEEVER", "Soul of Leevers (MM)"),
    OOTxMMItemData(586, "MM_SOUL_ENEMY_LIKE_LIKE", "Soul of Like Likes (MM)"),
    OOTxMMItemData(587, "MM_SOUL_ENEMY_LIZALFOS_DINALFOS", "Soul of Lizalfos/Dinolfos (MM)"),
    OOTxMMItemData(588, "MM_SOUL_ENEMY_NEJIRON", "Soul of Nejirons", type=filler),
    OOTxMMItemData(589, "MM_SOUL_ENEMY_OCTOROK", "Soul of Octoroks (MM)"),
    OOTxMMItemData(590, "MM_SOUL_ENEMY_PEAHAT", "Soul of Peahats (MM)"),
    OOTxMMItemData(591, "MM_SOUL_ENEMY_REAL_BOMBCHU", "Soul of Real Bombchu", type=filler),
    OOTxMMItemData(592, "MM_SOUL_ENEMY_REDEAD_GIBDO", "Soul of ReDeads/Gibdos (MM)"),
    OOTxMMItemData(593, "MM_SOUL_ENEMY_SHELL_BLADE", "Soul of Shell Blades (MM)"),
    OOTxMMItemData(594, "MM_SOUL_ENEMY_SKULLFISH", "Soul of Skullfish (MM)", type=filler),
    OOTxMMItemData(595, "MM_SOUL_ENEMY_SKULLTULA", "Soul of Skulltulas (MM)"),
    OOTxMMItemData(596, "MM_SOUL_ENEMY_SKULLWALLTULA", "Soul of Skullwalltulas (MM)"),
    OOTxMMItemData(597, "MM_SOUL_ENEMY_SNAPPER", "Soul of Snappers"),
    OOTxMMItemData(598, "MM_SOUL_ENEMY_STALCHILD", "Soul of Stalchildren (MM)"),
    OOTxMMItemData(599, "MM_SOUL_ENEMY_TAKKURI", "Soul of Takkuri", type=filler),
    OOTxMMItemData(600, "MM_SOUL_ENEMY_TEKTITE", "Soul of Tektites (MM)"),
    OOTxMMItemData(601, "MM_SOUL_ENEMY_THIEVES", "Soul of the Fighting Pirates"),
    OOTxMMItemData(602, "MM_SOUL_ENEMY_WALLMASTER", "Soul of Wallmasters (MM)"),
    OOTxMMItemData(603, "MM_SOUL_ENEMY_WART", "Soul of Warts"),
    OOTxMMItemData(604, "MM_SOUL_ENEMY_WIZZROBE", "Soul of Wizzrobes"),
    OOTxMMItemData(605, "MM_SOUL_ENEMY_WOLFOS", "Soul of Wolfos (MM)"),
    OOTxMMItemData(606, "MM_SOUL_MISC_BUSINESS_SCRUB", "Soul of Business Scrubs (MM)"),
    OOTxMMItemData(607, "MM_SOUL_MISC_GS", "Soul of Gold Skulltulas (MM)"),
    OOTxMMItemData(608, "MM_SOUL_NPC_ANJU", "Soul of Anju (MM)"),
    OOTxMMItemData(609, "MM_SOUL_NPC_AROMA", "Soul of Madame Aroma (MM)"),
    OOTxMMItemData(610, "MM_SOUL_NPC_ASTRONOMER", "Soul of Astronomer (MM)"),
    OOTxMMItemData(611, "MM_SOUL_NPC_BANKER", "Soul of the Banker (MM)"),
    OOTxMMItemData(612, "MM_SOUL_NPC_BAZAAR_SHOPKEEPER", "Soul of Swamp Archery Owner (MM)"),
    OOTxMMItemData(613, "MM_SOUL_NPC_BEAN_SALESMAN", "Soul of the Beans Salesman (MM)"),
    OOTxMMItemData(614, "MM_SOUL_NPC_BIGGORON", "Soul of Biggoron (MM)"),
    OOTxMMItemData(615, "MM_SOUL_NPC_BLACKSMITHS", "Soul of Blacksmiths"),
    OOTxMMItemData(616, "MM_SOUL_NPC_BOMBCHU_BOWLING_LADY", "Soul of Chest Game Lady (MM)"),
    OOTxMMItemData(617, "MM_SOUL_NPC_BOMBCHU_SHOPKEEPER", "Soul of the Bomb Shop Owner (MM)"),
    OOTxMMItemData(618, "MM_SOUL_NPC_BOMBERS", "Soul of Bombers (MM)"),
    OOTxMMItemData(619, "MM_SOUL_NPC_BUTLER_DEKU", "Soul of the Deku Butler"),
    OOTxMMItemData(620, "MM_SOUL_NPC_CARPENTERS", "Soul of Carpenters (MM)"),
    OOTxMMItemData(621, "MM_SOUL_NPC_CARPET_MAN", "Soul of Swordsman (MM)"),
    OOTxMMItemData(622, "MM_SOUL_NPC_CHEST_GAME_OWNER", "Soul of the Fisherman (MM)"),
    OOTxMMItemData(623, "MM_SOUL_NPC_CITIZEN", "Soul of Citizens (MM)"),
    OOTxMMItemData(624, "MM_SOUL_NPC_COMPOSER_BROS", "Soul of Composer Bros. (MM)"),
    OOTxMMItemData(625, "MM_SOUL_NPC_DAMPE", "Soul of Dampe (MM)"),
    OOTxMMItemData(626, "MM_SOUL_NPC_DEKU_KING", "Soul of the Deku King"),
    OOTxMMItemData(627, "MM_SOUL_NPC_DEKU_PRINCESS", "Soul of the Deku Princess"),
    OOTxMMItemData(628, "MM_SOUL_NPC_DOG_LADY", "Soul of Dog Lady (MM)"),
    OOTxMMItemData(629, "MM_SOUL_NPC_FISHING_POND_OWNER", "Soul of Trading Post Owner (MM)"),
    OOTxMMItemData(630, "MM_SOUL_NPC_GORMAN", "Soul of Gorman & Bros. (MM)"),
    OOTxMMItemData(631, "MM_SOUL_NPC_GORON", "Soul of Gorons (MM)"),
    OOTxMMItemData(632, "MM_SOUL_NPC_GORON_CHILD", "Soul of the Goron Baby (MM)"),
    OOTxMMItemData(633, "MM_SOUL_NPC_GORON_ELDER", "Soul of the Goron Elder"),
    OOTxMMItemData(634, "MM_SOUL_NPC_GORON_SHOPKEEPER", "Soul of the Goron Shopkeeper (MM)"),
    OOTxMMItemData(635, "MM_SOUL_NPC_GROG", "Soul of Grog (MM)"),
    OOTxMMItemData(636, "MM_SOUL_NPC_GURU_GURU", "Soul of Guru-Guru (MM)"),
    OOTxMMItemData(637, "MM_SOUL_NPC_HONEY_DARLING", "Soul of Honey & Darling (MM)"),
    OOTxMMItemData(638, "MM_SOUL_NPC_KAFEI", "Soul of Kafei"),
    OOTxMMItemData(639, "MM_SOUL_NPC_KEATON", "Soul of Keaton"),
    OOTxMMItemData(640, "MM_SOUL_NPC_KOUME_KOTAKE", "Soul of Koume and Kotake"),
    OOTxMMItemData(641, "MM_SOUL_NPC_MALON", "Soul of Romani/Cremia (MM)"),
    OOTxMMItemData(642, "MM_SOUL_NPC_MAYOR_DOTOUR", "Soul of Mayor Dotour"),
    OOTxMMItemData(643, "MM_SOUL_NPC_MEDIGORON", "Soul of Keg Trial Goron (MM)"),
    OOTxMMItemData(644, "MM_SOUL_NPC_MOON_CHILDREN", "Soul of Moon Children"),
    OOTxMMItemData(645, "MM_SOUL_NPC_OLD_HAG", "Soul of Anju's Grandmother (MM)"),
    OOTxMMItemData(646, "MM_SOUL_NPC_PLAYGROUND_SCRUBS", "Soul of Playground Scrubs"),
    OOTxMMItemData(647, "MM_SOUL_NPC_POE_COLLECTOR", "Soul of Ghost Hut Owner (MM)"),
    OOTxMMItemData(648, "MM_SOUL_NPC_ROOFTOP_MAN", "Soul of Part-Timer (MM)"),
    OOTxMMItemData(649, "MM_SOUL_NPC_RUTO", "Soul of Lulu (MM)"),
    OOTxMMItemData(650, "MM_SOUL_NPC_SCIENTIST", "Soul of the Scientist (MM)"),
    OOTxMMItemData(651, "MM_SOUL_NPC_SHOOTING_GALLERY_OWNER", "Soul of Town Archery Owner (MM)"),
    OOTxMMItemData(652, "MM_SOUL_NPC_TALON", "Soul of Mr. Barten (MM)"),
    OOTxMMItemData(653, "MM_SOUL_NPC_THIEVES", "Soul of the Patrolling Pirates and their Chief"),
    OOTxMMItemData(654, "MM_SOUL_NPC_TINGLE", "Soul of Tingle"),
    OOTxMMItemData(655, "MM_SOUL_NPC_TOILET_HAND", "Soul of Toilet Hand"),
    OOTxMMItemData(656, "MM_SOUL_NPC_TOTO", "Soul of Toto(MM)"),
    OOTxMMItemData(657, "MM_SOUL_NPC_TOURIST_CENTER", "Soul of Tourist Center Owner"),
    OOTxMMItemData(658, "MM_SOUL_NPC_ZORA", "Soul of Zoras (MM)"),
    OOTxMMItemData(659, "MM_SOUL_NPC_ZORA_MUSICIANS", "Soul of the Zora Musicians"),
    OOTxMMItemData(660, "MM_SOUL_NPC_ZORA_SHOPKEEPER", "Soul of the Zora Shopkeeper (MM)"),
    OOTxMMItemData(661, "MM_SPELL_FIRE", "Din's Fire (MM)"),
    OOTxMMItemData(662, "MM_SPELL_LOVE", "Nayru's Love (MM)"),
    OOTxMMItemData(663, "MM_SPELL_WIND", "Farore's Wind (MM)"),
    OOTxMMItemData(664, "MM_SPIN_UPGRADE", "Spin Attack Upgrade (MM)"),
    OOTxMMItemData(665, "MM_STICK", "Deku Stick (MM)", type=filler),
    OOTxMMItemData(666, "MM_STICK_UPGRADE", "Deku Stick Upgrade (MM)", type=useful),
    OOTxMMItemData(667, "MM_STONE_OF_AGONY", "Stone of Agony (MM)"),
    OOTxMMItemData(668, "MM_STRAY_FAIRY_GB", "Stray Fairy (Great Bay Temple)"),
    OOTxMMItemData(669, "MM_STRAY_FAIRY_SH", "Stray Fairy (Snowhead Temple)"),
    OOTxMMItemData(670, "MM_STRAY_FAIRY_ST", "Stray Fairy (Stone Tower Temple)"),
    OOTxMMItemData(671, "MM_STRAY_FAIRY_TOWN", "Stray Fairy (Clock Town)"),
    OOTxMMItemData(672, "MM_STRAY_FAIRY_WF", "Stray Fairy (Woodfall Temple)"),
    OOTxMMItemData(673, "MM_STRENGTH", "Progressive Strength (MM)"),
    OOTxMMItemData(674, "MM_SWORD", "Progressive Sword (MM)"),
    OOTxMMItemData(675, "MM_TRAP_RUPOOR", "Rupoor (MM)", type=trap),
    OOTxMMItemData(676, "MM_TUNIC_GORON", "Goron Tunic (MM)"),
    OOTxMMItemData(677, "MM_TUNIC_ZORA", "Zora Tunic (MM)"),
    OOTxMMItemData(678, "MM_WALLET", "Progressive Wallet (MM)"),
    OOTxMMItemData(679, "MM_WORLD_MAP_CLOCK_TOWN", "World Map of Clock Town", type=useful),
    OOTxMMItemData(680, "MM_WORLD_MAP_GREAT_BAY", "World Map of Great Bay", type=useful),
    OOTxMMItemData(681, "MM_WORLD_MAP_ROMANI_RANCH", "World Map of Ranch", type=useful),
    OOTxMMItemData(682, "MM_WORLD_MAP_SNOWHEAD", "World Map of Snowhead", type=useful),
    OOTxMMItemData(683, "MM_WORLD_MAP_STONE_TOWER", "World Map of Stone Tower", type=useful),
    OOTxMMItemData(684, "MM_WORLD_MAP_WOODFALL", "World Map of Woodfall", type=useful),
    OOTxMMItemData(685, "NOTHING", "Nothing", type=trap),
    OOTxMMItemData(686, "SHARED_ARROW_FIRE", "Shared Fire Arrows"),
    OOTxMMItemData(687, "SHARED_ARROW_ICE", "Shared Ice Arrows"),
    OOTxMMItemData(688, "SHARED_ARROW_LIGHT", "Shared Light Arrows"),
    OOTxMMItemData(689, "SHARED_ARROWS_5", "5 Arrows", type=filler),
    OOTxMMItemData(690, "SHARED_ARROWS_10", "10 Arrows", type=filler),
    OOTxMMItemData(691, "SHARED_ARROWS_30", "30 Arrows", type=filler),
    OOTxMMItemData(692, "SHARED_ARROWS_40", "40 Arrows", type=filler),
    OOTxMMItemData(693, "SHARED_BOMB", "1 Bomb", type=filler),
    OOTxMMItemData(694, "SHARED_BOMB_BAG", "Shared Bomb Bag"),
    OOTxMMItemData(695, "SHARED_BOMBCHU", "Bombchu"),
    OOTxMMItemData(696, "SHARED_BOMBCHU_5", "5 Bombchu"),
    OOTxMMItemData(697, "SHARED_BOMBCHU_10", "10 Bombchu"),
    OOTxMMItemData(698, "SHARED_BOMBCHU_20", "20 Bombchu"),
    OOTxMMItemData(699, "SHARED_BOMBCHU_BAG", "Bombchu Bag"),
    OOTxMMItemData(700, "SHARED_BOMBS_5", "5 Bombs", type=filler),
    OOTxMMItemData(701, "SHARED_BOMBS_10", "10 Bombs", type=filler),
    OOTxMMItemData(702, "SHARED_BOMBS_20", "20 Bombs", type=filler),
    OOTxMMItemData(703, "SHARED_BOMBS_30", "30 Bombs", type=filler),
    OOTxMMItemData(704, "SHARED_BOOTS_HOVER", "Hover Boots"),
    OOTxMMItemData(705, "SHARED_BOOTS_IRON", "Iron Boots"),
    OOTxMMItemData(706, "SHARED_BOW", "Shared Bow"),
    OOTxMMItemData(707, "SHARED_BUTTON_A", "A Button"),
    OOTxMMItemData(708, "SHARED_BUTTON_C_DOWN", "C-Down Button"),
    OOTxMMItemData(709, "SHARED_BUTTON_C_LEFT", "C-Left Button"),
    OOTxMMItemData(710, "SHARED_BUTTON_C_RIGHT", "C-Right Button"),
    OOTxMMItemData(711, "SHARED_BUTTON_C_UP", "C-Up Button"),
    OOTxMMItemData(712, "SHARED_DEFENSE_UPGRADE", "Double Defense", type=useful),
    OOTxMMItemData(713, "SHARED_FAIRY_BIG", "Big Fairy", type=filler),
    OOTxMMItemData(714, "SHARED_HAMMER", "Megaton Hammer"),
    OOTxMMItemData(715, "SHARED_HEART_CONTAINER", "Heart Container", type=useful),
    OOTxMMItemData(716, "SHARED_HEART_PIECE", "Piece of Heart", type=useful),
    OOTxMMItemData(717, "SHARED_HOOKSHOT", "Progressive Hookshot"),
    OOTxMMItemData(718, "SHARED_LENS", "Lens of Truth"),
    OOTxMMItemData(719, "SHARED_MAGIC_JAR_LARGE", "Large Magic Jar", type=filler),
    OOTxMMItemData(720, "SHARED_MAGIC_JAR_SMALL", "Small Magic Jar", type=filler),
    OOTxMMItemData(721, "SHARED_MAGIC_UPGRADE", "Shared Magic Upgrade"),
    OOTxMMItemData(722, "SHARED_MASK_BLAST", "Blast Mask"),
    OOTxMMItemData(723, "SHARED_MASK_BUNNY", "Bunny Hood"),
    OOTxMMItemData(724, "SHARED_MASK_GORON", "Goron Mask"),
    OOTxMMItemData(725, "SHARED_MASK_KEATON", "Keaton Mask"),
    OOTxMMItemData(726, "SHARED_MASK_STONE", "Stone Mask"),
    OOTxMMItemData(727, "SHARED_MASK_TRUTH", "Mask of Truth"),
    OOTxMMItemData(728, "SHARED_MASK_ZORA", "Zora Mask"),
    OOTxMMItemData(729, "SHARED_NUT", "Deku Nut", type=filler),
    OOTxMMItemData(730, "SHARED_NUT_UPGRADE", "Deku Nut Upgrade", type=useful),
    OOTxMMItemData(731, "SHARED_NUTS_5", "5 Deku Nuts", type=filler),
    OOTxMMItemData(732, "SHARED_NUTS_10", "10 Deku Nuts", type=filler),
    OOTxMMItemData(733, "SHARED_OCARINA", "Progressive Ocarina"),
    OOTxMMItemData(734, "SHARED_RECOVERY_HEART", "Recovery Heart", type=filler),
    OOTxMMItemData(735, "SHARED_RUPEE_BLUE", "Blue Rupee", type=filler),
    OOTxMMItemData(736, "SHARED_RUPEE_GOLD", "Gold Rupee", type=filler),
    OOTxMMItemData(737, "SHARED_RUPEE_GREEN", "Green Rupee", type=filler),
    OOTxMMItemData(738, "SHARED_RUPEE_PURPLE", "Purple Rupee", type=filler),
    OOTxMMItemData(739, "SHARED_RUPEE_RAINBOW", "Rainbow Rupee", type=useful),
    OOTxMMItemData(740, "SHARED_RUPEE_RED", "Red Rupee", type=filler),
    OOTxMMItemData(741, "SHARED_RUPEE_SILVER", "Silver Rupee", type=filler),
    OOTxMMItemData(742, "SHARED_SCALE", "Progressive Scale"),
    OOTxMMItemData(743, "SHARED_SHIELD", "Progressive Shield"),
    OOTxMMItemData(744, "SHARED_SHIELD_DEKU", "Deku Shield", type=useful),
    OOTxMMItemData(745, "SHARED_SHIELD_HYLIAN", "Hylian/Hero Shield", type=useful),
    OOTxMMItemData(746, "SHARED_SHIELD_MIRROR", "Mirror Shield"),
    OOTxMMItemData(747, "SHARED_SKELETON_KEY", "Skeleton Key"),
    OOTxMMItemData(748, "SHARED_SONG_EMPTINESS", "Elegy of Emptiness"),
    OOTxMMItemData(749, "SHARED_SONG_EPONA", "Epona's Song"),
    OOTxMMItemData(750, "SHARED_SONG_STORMS", "Song of Storms"),
    OOTxMMItemData(751, "SHARED_SONG_SUN", "Sun's Song"),
    OOTxMMItemData(752, "SHARED_SONG_TIME", "Song of Time"),
    OOTxMMItemData(753, "SHARED_SOUL_ENEMY_ARMOS", "Soul of Armos"),
    OOTxMMItemData(754, "SHARED_SOUL_ENEMY_BEAMOS", "Soul of Beamos"),
    OOTxMMItemData(755, "SHARED_SOUL_ENEMY_BUBBLE", "Soul of Bubbles"),
    OOTxMMItemData(756, "SHARED_SOUL_ENEMY_DEKU_BABA", "Soul of Deku Babas"),
    OOTxMMItemData(757, "SHARED_SOUL_ENEMY_DEKU_SCRUB", "Soul of Deku Scrubs"),
    OOTxMMItemData(758, "SHARED_SOUL_ENEMY_DODONGO", "Soul of Dodongos"),
    OOTxMMItemData(759, "SHARED_SOUL_ENEMY_FLOORMASTER", "Soul of Floormasters"),
    OOTxMMItemData(760, "SHARED_SOUL_ENEMY_FLYING_POT", "Soul of Flying Pots"),
    OOTxMMItemData(761, "SHARED_SOUL_ENEMY_FREEZARD", "Soul of Freezards"),
    OOTxMMItemData(762, "SHARED_SOUL_ENEMY_GUAY", "Soul of Guays"),
    OOTxMMItemData(763, "SHARED_SOUL_ENEMY_IRON_KNUCKLE", "Soul of Iron Knuckles"),
    OOTxMMItemData(764, "SHARED_SOUL_ENEMY_KEESE", "Soul of Keese"),
    OOTxMMItemData(765, "SHARED_SOUL_ENEMY_LEEVER", "Soul of Leevers"),
    OOTxMMItemData(766, "SHARED_SOUL_ENEMY_LIKE_LIKE", "Soul of Like Likes"),
    OOTxMMItemData(767, "SHARED_SOUL_ENEMY_LIZALFOS_DINALFOS", "Soul of Lizalfos/Dinolfos"),
    OOTxMMItemData(768, "SHARED_SOUL_ENEMY_OCTOROK", "Soul of Octoroks"),
    OOTxMMItemData(769, "SHARED_SOUL_ENEMY_PEAHAT", "Soul of Peahats"),
    OOTxMMItemData(770, "SHARED_SOUL_ENEMY_REDEAD_GIBDO", "Soul of ReDeads/Gibdos"),
    OOTxMMItemData(771, "SHARED_SOUL_ENEMY_SHELL_BLADE", "Soul of Shell Blades"),
    OOTxMMItemData(772, "SHARED_SOUL_ENEMY_SKULLTULA", "Soul of Skulltulas"),
    OOTxMMItemData(773, "SHARED_SOUL_ENEMY_SKULLWALLTULA", "Soul of Skullwalltulas"),
    OOTxMMItemData(774, "SHARED_SOUL_ENEMY_STALCHILD", "Soul of Stalchildren"),
    OOTxMMItemData(775, "SHARED_SOUL_ENEMY_TEKTITE", "Soul of Tektites"),
    OOTxMMItemData(776, "SHARED_SOUL_ENEMY_THIEVES", "Soul of Fighting Thieves"),
    OOTxMMItemData(777, "SHARED_SOUL_ENEMY_WALLMASTER", "Soul of Wallmasters"),
    OOTxMMItemData(778, "SHARED_SOUL_ENEMY_WOLFOS", "Soul of Wolfos"),
    OOTxMMItemData(779, "SHARED_SOUL_MISC_BUSINESS_SCRUB", "Soul of Business Scrubs"),
    OOTxMMItemData(780, "SHARED_SOUL_MISC_GS", "Soul of Gold Skulltulas"),
    OOTxMMItemData(781, "SHARED_SOUL_NPC_ANJU", "Soul of Cucco Lady/Anju"),
    OOTxMMItemData(782, "SHARED_SOUL_NPC_ASTRONOMER", "Soul of the Astronomer"),
    OOTxMMItemData(783, "SHARED_SOUL_NPC_BANKER", "Soul of the Beggar/Banker"),
    OOTxMMItemData(784, "SHARED_SOUL_NPC_BAZAAR_SHOPKEEPER", "Soul of the Bazaar/Swamp Archery Owner"),
    OOTxMMItemData(785, "SHARED_SOUL_NPC_BEAN_SALESMAN", "Soul of the Bean Salesman"),
    OOTxMMItemData(786, "SHARED_SOUL_NPC_BIGGORON", "Soul of Biggoron"),
    OOTxMMItemData(787, "SHARED_SOUL_NPC_BOMBCHU_BOWLING_LADY", "Soul of Bombchu Bowling/Chest Game Lady"),
    OOTxMMItemData(788, "SHARED_SOUL_NPC_BOMBCHU_SHOPKEEPER", "Soul of the Bombchu/Bomb Shop Owner"),
    OOTxMMItemData(789, "SHARED_SOUL_NPC_BOMBERS", "Soul of the Graveyard Kid/Bombers"),
    OOTxMMItemData(790, "SHARED_SOUL_NPC_CARPENTERS", "Soul of Carpenters"),
    OOTxMMItemData(791, "SHARED_SOUL_NPC_CARPET_MAN", "Soul of the Carpet Man/Swordsman"),
    OOTxMMItemData(792, "SHARED_SOUL_NPC_CHEST_GAME_OWNER", "Soul of the Chest Game Owner/Fisherman"),
    OOTxMMItemData(793, "SHARED_SOUL_NPC_CITIZEN", "Soul of Citizens"),
    OOTxMMItemData(794, "SHARED_SOUL_NPC_COMPOSER_BROS", "Soul of Composer Bros."),
    OOTxMMItemData(795, "SHARED_SOUL_NPC_DAMPE", "Soul of Dampe"),
    OOTxMMItemData(796, "SHARED_SOUL_NPC_DOG_LADY", "Soul of the Dog Lady"),
    OOTxMMItemData(797, "SHARED_SOUL_NPC_FISHING_POND_OWNER", "Soul of Fishing Pond/Trading Post Owner"),
    OOTxMMItemData(798, "SHARED_SOUL_NPC_GORMAN", "Soul of Ingo/Gorman & Bros."),
    OOTxMMItemData(799, "SHARED_SOUL_NPC_GORON", "Soul of Gorons"),
    OOTxMMItemData(800, "SHARED_SOUL_NPC_GORON_CHILD", "Soul of the Goron Child/Baby"),
    OOTxMMItemData(801, "SHARED_SOUL_NPC_GORON_SHOPKEEPER", "Soul of the Goron Shopkeeper"),
    OOTxMMItemData(802, "SHARED_SOUL_NPC_GROG", "Soul of the Punk Kid/Grog"),
    OOTxMMItemData(803, "SHARED_SOUL_NPC_GURU_GURU", "Soul of Guru-Guru"),
    OOTxMMItemData(804, "SHARED_SOUL_NPC_HONEY_DARLING", "Soul of Honey & Darling"),
    OOTxMMItemData(805, "SHARED_SOUL_NPC_MALON", "Soul of Malon/Romani/Cremia"),
    OOTxMMItemData(806, "SHARED_SOUL_NPC_MEDIGORON", "Soul of Medigoron/Keg Trial Goron"),
    OOTxMMItemData(807, "SHARED_SOUL_NPC_OLD_HAG", "Soul of the Old Hag/Anju's Grandmother"),
    OOTxMMItemData(808, "SHARED_SOUL_NPC_POE_COLLECTOR", "Soul of Poe Collector/Ghost Hut Owner"),
    OOTxMMItemData(809, "SHARED_SOUL_NPC_ROOFTOP_MAN", "Soul of Rooftop Man/Part-Timer"),
    OOTxMMItemData(810, "SHARED_SOUL_NPC_RUTO", "Soul of Ruto/Lulu"),
    OOTxMMItemData(811, "SHARED_SOUL_NPC_SCIENTIST", "Soul of the Scientist"),
    OOTxMMItemData(812, "SHARED_SOUL_NPC_SHOOTING_GALLERY_OWNER", "Soul of the Shooting Gallery/Town Archery Owner"),
    OOTxMMItemData(813, "SHARED_SOUL_NPC_TALON", "Soul of Talon/Mr. Barten"),
    OOTxMMItemData(814, "SHARED_SOUL_NPC_THIEVES", "Soul of the Patrolling Thieves and their Chief"),
    OOTxMMItemData(815, "SHARED_SOUL_NPC_ZORA", "Soul of Zoras"),
    OOTxMMItemData(816, "SHARED_SOUL_NPC_ZORA_SHOPKEEPER", "Soul of the Zora Shopkeeper"),
    OOTxMMItemData(817, "SHARED_SPELL_FIRE", "Din's Fire"),
    OOTxMMItemData(818, "SHARED_SPELL_LOVE", "Nayru's Love"),
    OOTxMMItemData(819, "SHARED_SPELL_WIND", "Farore's Wind"),
    OOTxMMItemData(820, "SHARED_SPIN_UPGRADE", "Spin Attack Upgrade"),
    OOTxMMItemData(821, "SHARED_STICK", "Deku Stick", type=filler),
    OOTxMMItemData(822, "SHARED_STICK_UPGRADE", "Deku Stick Upgrade", type=useful),
    OOTxMMItemData(823, "SHARED_STICKS_5", "5 Deku Sticks", type=filler),
    OOTxMMItemData(824, "SHARED_STICKS_10", "10 Deku Sticks", type=filler),
    OOTxMMItemData(825, "SHARED_STONE_OF_AGONY", "Stone of Agony"),
    OOTxMMItemData(826, "SHARED_STRENGTH", "Progressive Strength"),
    OOTxMMItemData(827, "SHARED_SWORD", "Progressive Sword"),
    OOTxMMItemData(828, "SHARED_TRAP_RUPOOR", "Rupoor", type=trap),
    OOTxMMItemData(829, "SHARED_TRIFORCE", "Triforce Piece"),
    OOTxMMItemData(830, "SHARED_TRIFORCE_COURAGE", "Triforce of Courage"),
    OOTxMMItemData(831, "SHARED_TRIFORCE_POWER", "Triforce of Power"),
    OOTxMMItemData(832, "SHARED_TRIFORCE_WISDOM", "Triforce of Wisdom"),
    OOTxMMItemData(833, "SHARED_TUNIC_GORON", "Goron Tunic"),
    OOTxMMItemData(834, "SHARED_TUNIC_ZORA", "Zora Tunic"),
    OOTxMMItemData(835, "SHARED_WALLET", "Progressive Wallet"),
    OOTxMMItemData(836, "FILL_RUPPEE", "FILL RUPPEE", type=filler),
]

ITEM_NAME_TO_ID = {item.display_name: item.id for item in OOTxMMItemList}

def get_item_id_by_name(item_name: str) -> int:
    return ITEM_NAME_TO_ID[item_name]

def get_item_class_by_id(item_id: int) -> ItemClassification:
    return OOTxMMItemList[item_id-1].type

def get_random_filler_item(world: OOTxMM) -> str:
    return "FILL RUPPEE"

def create_item_with_correct_classification(world: OOTxMM, item_name: str) -> OOTxMMItem:
    return OOTxMMItem(item_name, get_item_class_by_id(get_item_id_by_name(item_name)), ITEM_NAME_TO_ID[item_name], world.player)

# With those two helper functions defined, let's now get to actually creating and submitting our itempool.
def create_all_items(world: OOTxMM) -> None:
    print(OOTxMMItemList)
    print("-----")
    print(get_item_id_by_name("FILL RUPPEE"))
    
    itempool: list[Item] = [create_item_with_correct_classification(world, item.display_name) for item in OOTxMMItemList]
    number_of_items = len(itempool)
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    needed_number_of_filler_items = number_of_unfilled_locations - number_of_items
    
    print("Number of items:", number_of_items)
    print("Number of unfilled locations:", number_of_unfilled_locations)
    print("Number of items:", needed_number_of_filler_items)
    for thing in itempool:
        print(thing)
        print(type(thing))
    
    
    itempool += [world.create_filler() for _ in range(needed_number_of_filler_items)]
    world.multiworld.itempool += itempool
